### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dr3st** [seanauff/WOL-proxy#1]
Hey ho @seanauff ,

first of all I would like to thank you for offering this project. I think this is very helpful for isolated docker containers (like homeassistant), where WOL is not possible to forward to other networks.

So I would like to use your source code and improve the Dockerfile by non-root, linuxserver.io base image and such things, but I did not found any license.

To be fair, I may ask you to define a License, or give your "okay" for forking and editing source code...

Thank you in advance :)

**Comment by seanauff** [comment]
Thanks for bringing this up. I just added a license file. Fork away!
