### ISSUE TITLE
Compatibility Issue with paho-mqtt Version 2.0.0 in WOL-proxy

### ISSUE THREAD

**Issue by Bukisoo** [seanauff/WOL-proxy#3]
### Title
Compatibility Issue with `paho-mqtt` Version 2.0.0 in `WOL-proxy`

### Body
**Description:**  
After updating to `paho-mqtt` version 2.0.0, the `WOL-proxy` application fails to start due to breaking changes introduced in the `paho-mqtt` library. Specifically, the new requirement for a `callback_api_version` argument in the `Client` class constructor causes the application to exit with a `TypeError`.

**Steps to Reproduce:**  
1. Run the Docker container for `WOL-proxy` using the latest `python:3-slim-buster` image, which installs the latest version of `paho-mqtt` by default.  
2. Observe the application failing to start, logging a `TypeError` related to the `Client` object initialization.

**Expected Behavior:**  
The `WOL-proxy` application starts successfully and operates as intended without exiting due to errors related to library dependencies.

**Actual Behavior:**  
The application exits immediately after starting, with the logs indicating a `TypeError` due to a missing `callback_api_version` argument in the `Client` constructor, as required by `paho-mqtt` version 2.0.0.

**Environment:**  
- Docker Image Base: `python:3-slim-buster`  
- `paho-mqtt` Version: 2.0.0  

**Possible Solutions:**  
1. **Update the `WOL-proxy` Application:** Modify the `Client` object initialization in the `WOL-proxy.py` script to include the `callback_api_version` argument as per the new requirements of `paho-mqtt` version 2.0.0.  
2. **Specify a Compatible `paho-mqtt` Version:** Adjust the Dockerfile to install a specific version of `paho-mqtt` that is known to be compatible with `WOL-proxy`, e.g., `paho-mqtt==1.6.1`. This can be achieved by modifying the `RUN pip install` command as follows:  
   ```dockerfile
   RUN pip install paho-mqtt==1.6.1 wakeonlan

**Comment by seanauff** [comment]
Hello, the code has been updated for paho-mqtt version 2 and new docker images have been built and tested working.

#4
